build:
  script:
    -   mkdir build
    -   cd build
    -   cmake .. -DTEST=on
    -   make
    -   ./MXCoreTest
        
pages:
  script:
  - doxygen Doxyfile
  - mv Doc/html/ public/
  artifacts:
    paths:
    - public
